### ISSUE TITLE
Allow files to be saved with spaces in the file name

### ISSUE THREAD

**Issue by seanmcclure22** [electron-userland/electron-json-storage#100]
Hi!

So I am running into an issue where I am building an electron app to be used in windows environments and because of line 123 in utils.js the `encodeURIComponent` method replaces spaces in file names with %20. Saving files with a space in the name is allowed in modern operating systems, and they even mention that you may want to modify the `encodeURIComponent` method on the [official documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent). 

Since this package is exclusively used for desktop applications, would it be possible to allow spaces in file names? I believe you could accomplish this with a method like: 
``` javascript
function fixedEncodeURIComponent(str) {
  return encodeURIComponent(str).replace(/%20/g, function(c) {
    return ' ';
  });
}
```

Thanks!

**Comment by jakehockey10** [comment]
I am running into this issue as well

**Comment by jviotti** [comment]
Hey there! Thank for reporting. I'm happy to take a PR that adds this change and runs a couple of unit tests. If all the platforms agree with this change, then we should be good to go.
