### ISSUE TITLE
Electron dependency breaks electron-builder via Mac App Store

### ISSUE THREAD

**Issue by james-criscuolo** [electron-userland/electron-json-storage#112]
The electron dependency introduced here: https://github.com/electron-userland/electron-json-storage/commit/7f035f2cf54038c9c45026d977d8556d45706fc9

Causes node_modules to have multiple electron dependencies, or maybe just 1, but typically this is not here. I didn't mess around much, but even setting it to the same version of electron was causing issues. This causes the pList files generated for the Mac App Store to include multiple references to electron, which is not allowed. Is there any reason this isn't just a peer dependency?

**Comment by jviotti** [comment]
Hi @james-criscuolo ,

Thanks for the heads up. This should have been a peer dependency, as you pointed out. Can you send a PR for it? I'll merge and publish right away!

**Comment by james-criscuolo** [comment]
I see another user already covered this in #114, please let me know if there is anything else I can do.

**Comment by jviotti** [comment]
I published the fix as v4.1.2. I'll close this ticket now, but please let us know how it went :)
