### ISSUE TITLE
Electron Dependencies break electron builder on windows

### ISSUE THREAD

**Issue by z687wang** [electron-userland/electron-json-storage#113]
Extra files was generated after build process.
an electron sample app got packed into /app.asar.unpacked/node_modules/electron-json-storage/node_modules/electron/

**Comment by a-lizards-breath** [comment]
where did the sample app come from?? Thinking of including this for simple key/val storage in a windows target app, but that sounds.... troubling

**Comment by jviotti** [comment]
Yeah, `electron` should have been a `peerDependency`. Feel free to send a PR :)

**Comment by Slapbox** [comment]
Sent a PR for this earlier. Just mentioning so no one else needlessly does it again.

**Comment by jviotti** [comment]
I published the fix as v4.1.2. I'll close this ticket now, but please let us know how it went :)

**Comment by z687wang** [comment]
@jviotti Thank you.
