### ISSUE TITLE
Electron dependency gets packaged into resource

### ISSUE THREAD

**Issue by bingqiao** [electron-userland/electron-json-storage#120]
I think this issue was raised in [133](https://github.com/electron-userland/electron-json-storage/issues/113). It is however the **electron dependency**, not a sample app, being packed into resource.

And that fix in 4.1.2 does not work. Electron dependency still gets packed into win-unpacked\resources\app.asar.unpacked\node_modules by electron-builder. Why does electron need to be a dependency/peerdependency for electron-json-storage? Should it be just devDependencies instead?

This only started happening since 4.1.1.

Thanks

**Comment by jviotti** [comment]
Hey there!

You're right! Can you try v4.1.4?

**Comment by bingqiao** [comment]
Yes it now has been fixed. Thanks
