### ISSUE TITLE
Warning upon building with 4.1.6 (latest)

### ISSUE THREAD

**Issue by james-criscuolo** [electron-userland/electron-json-storage#126]
I'm seeing a new warning when building with webpack, it's an angular AOT build:
```
WARNING in ./node_modules/electron-json-storage/node_modules/write-file-atomic/index.js
Module not found: Error: Can't resolve 'worker_threads' in '/{path_to_my_project}/node_modules/electron-json-storage/node_modules/write-file-atomic'
 @ ./node_modules/electron-json-storage/node_modules/write-file-atomic/index.js
 @ ./node_modules/electron-json-storage/lib/storage.js
 @ {where my import is}
```
This does not appear to break my build, so it does not look like I'll need to go to an earlier version. I import a non-standard way, but it appears the recommended way also causes it:
```
// import * as desktopStorage from "electron-json-storage";
const desktopStorage = require("electron-json-storage");
```
(both cause the issue)
I can also confirm this does not occur with 4.1.5

**Comment by jviotti** [comment]
Hey @james-criscuolo ,

That looks like an issue on `write-file-atomic`, so I'd suggest re-opening this issue there. I believe it works fine in previous versions because this module started requiring `write-file-atomic` quite recently!

**Comment by james-criscuolo** [comment]
Closing this as Node 12 is now LTS, and it doesn't occur there.
