### ISSUE TITLE
Is this package still mainated?

### ISSUE THREAD

**Issue by laszukdawid** [electron-userland/electron-json-storage#140]
Saw mentioning of this package in one of the [stackoverflow questions](https://stackoverflow.com/a/35005205/2687601) and thought about giving it a shot. However, checking this GitHub page I see that the dependencies are outdated and there are plenty of old tickets. Is anyone still looking at this repo?

**Comment by jviotti** [comment]
Hi @laszukdawid, I try to keep an eye on the project as time permits, but I'd love to get some help with things like outdated dependencies or some of the feature requests. I'll review any incoming PRs!
