### ISSUE TITLE
Electron v14 support

### ISSUE THREAD

**Issue by juanmartin** [electron-userland/electron-json-storage#168]
Hi, I've just updated Electron to latest v14.0.1 and can't set the data path.
I always get the `Error: You must explicitly set a data path`.

This is my config for the main Window:
```js
webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true, // also tried with false, without success
}
```

I've used `storage.setDataPath(storagePath);` where I pass the `storagePath` through IPC to the renderer process.
Also tried setting the data path in the main process, but still get the error.
Calling `storage.getDefaultDataPath()` returns `null`
Calling `storage.getDataPath()` returns the set path.

I've migrated the project to use '@electron/remote' as it has been fully deprecated.

Let me know what other info can I provide to help debug this.

Thank you in advance!

**Comment by jviotti** [comment]
Glad you got it solved!
