### ISSUE TITLE
'The "path" argument must be of type string. Received null' in electron-json-storage

### ISSUE THREAD

**Issue by kochizufan** [electron-userland/electron-json-storage#179]
Maybe this post is kinda multi-post, but I want to fix this ASAP..

https://stackoverflow.com/questions/71897989/the-path-argument-must-be-of-type-string-received-null-in-electron-json-sto

**Comment by jviotti** [comment]
Can you create an [Electron Fiddle](https://www.electronjs.org/fiddle) or a basic repo reproducing the issue?

**Comment by kochizufan** [comment]
Sorry I found the reason...

I call "electron-json-storage" inside of "preload.js".
I don't know "preload.js" is worked on renderer process.
I must use electron-json-storage on main process.

I realized that under the contextIsolation environment, I need to completely rethink my architecture from the nodeIntegration era configuration.

**Comment by kochizufan** [comment]
I created example for using electron-json-storage under contextIsolation environment for people who will have similar question in future:
https://gist.github.com/kochizufan/a467c6b76390c6f1c41260614cb06a5c

This works well.

Any points for improvement are welcome.
