### ISSUE TITLE
Missing data from time to time

### ISSUE THREAD

**Issue by djalmaaraujo** [electron-userland/electron-json-storage#40]
I have an electron app, and for some reason, the storage is being deleted when I open the app again a few days later.

Is that common? I don't know how to provide more info about the problem. Let me know what I can send to explain more.

**Comment by jviotti** [comment]
Hey there!

That is not common at all! Could it be that something else is deleting
your storage? Do you have the application somewhere so I can try it
myself?

On Wed, Dec 14, 2016 at 09:33:43AM -0800, Djalma Araújo wrote:
> I have an electron app, and for some reason, the storage is being deleted when I open the app again a few days later.
> 
> Is that common? I don't know how to provide more info about the problem. Let me know what I can send to explain more.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jviotti/electron-json-storage/issues/40

-- 
Juan Cruz Viotti
Software Engineer

**Comment by bithavoc** [comment]
I'm also seeing this, MacOS High Sierra.
> electron-json-storage: 4.0.2
> electron: 1.7.9

This is the app's Application Support directory:


<img width="630" alt="33726905-6b7bf3d0-db44-11e7-9221-f2dc6e46a500" src="https://user-images.githubusercontent.com/219289/34613205-f5882ad6-f1fa-11e7-9558-c95a574c8a50.png">

**Comment by cryppadotta** [comment]
I'm also having the same problem on MacOS -- The file will write either an empty file or just the value `undefined`.

**Comment by bithavoc** [comment]
In my case the file is always empty, it's really hard to reproduce.

**Comment by jviotti** [comment]
What version are you guys running? Do you have an example code I could try? The following PR (https://github.com/electron-userland/electron-json-storage/pull/72) added a lock to protect from parallel writes, and the latest version test suite validates that no corruption happens even after writing and reading from the same file thousands of times.

**Comment by oscar-renteria** [comment]
Is there any progress on this? I have the same problem. Sometimes the .json file is empty. I have seen this under Windows and Linux with electron-json-storage v4.0.2.

**Comment by bithavoc** [comment]
@oscar-renteria I've seen it on Mac too, it's annoying and we haven't been able to launch because of it. At first I thought it was electron built-in updater but without any update it still breaks and the json file becomes empty.

**Comment by jviotti** [comment]
@oscar-renteria @bithavoc As mentioned above, we recently introduced locking on writes and we do stress testing to attempt to detect this. Is there any way I can reproduce?

**Comment by oscar-renteria** [comment]
@jviotti Unfortunately no. I cannot reproduce it. It happens sporadically from time to time. Does the latest version (4.1.0) implement the lock feature? I would like to give it a try.

**Comment by bithavoc** [comment]
I'll switch to the latest version and report back.

**Comment by oscar-renteria** [comment]
Hi @jviotti , is the lock feature on v3.0.6 you are talking about?

![image](https://user-images.githubusercontent.com/20833418/42270601-9438f43a-7f81-11e8-8b0b-d3051840bb5f.png)

Or you just have implemented something new which is being tested?

**Comment by jviotti** [comment]
@oscar-renteria @bithavoc That's correct. Such change came with this stress testing case (https://github.com/electron-userland/electron-json-storage/blob/master/tests/storage.spec.js#L70) that did reveal a similar problem.

There must be something else going-on in that case. Is there a way I can try the app you guys have? What kind of data are you writing, and on what OSes are you seeing the problem?

**Comment by jviotti** [comment]
@bithavoc @oscar-renteria Can you guys clone this project and run `npm test` on it on a machine that could reproduce this problem?

**Comment by bithavoc** [comment]
@jviotti I tried a few months back, the test suite passes locally.

You can try on your own, it's random and I haven't been able to reproduce consistently, but basically if the app kicks you out that means the state was lost. http://getgreensand.com/downloads/

We only have builds for Mac and Linux, only Mac users are experiencing it.

Could it have something to do with APFS?

**Comment by jviotti** [comment]
@bithavoc Cool, I'll give it a shot. Are you using different instances of this module in different processes? The locking we implemented only works if you're using `electron-json-storage` on one process, and doesn't protect you if you are writing to the same file from different processes.

I think if you can describe how you use this module in more detail (ie what processes use it, to write what files, etc) that might help pinning down the issue.

**Comment by jviotti** [comment]
Hi @bithavoc @oscar-renteria ,

I managed to reproduce this! I upgrade all the electron-related dependencies on this module (check master), and then increased the number of parallel writes we do during the stress testing phase, and that indeed revealed some issues!

```diff
diff --git a/tests/storage.spec.js b/tests/storage.spec.js
index 6d53905..2a6f348 100644
--- a/tests/storage.spec.js
+++ b/tests/storage.spec.js
@@ -50,7 +50,7 @@ describe('Electron JSON Storage', function() {

   describe('stress testing', function() {

-    const cases = _.times(1000, () => {
+    const cases = _.times(1000000, () => {
       return Math.floor(Math.random() * 100000);
     });
```

This is what I got on macOS Sierra:

```
  2) Electron JSON Storage
       stress testing
         should survive parallel stress testing:
     Uncaught AssertionError: expected [Error: Invalid data: ] to not exist
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at Assertion.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:286:25)
      at Assertion.get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at /Users/jviotti/Projects/personal/electron-json-storage/tests/storage.spec.js:77:40
      at /Users/jviotti/Projects/personal/electron-json-storage/node_modules/async/dist/async.js:473:16
      at next (node_modules/async/dist/async.js:5329:29)
      at /Users/jviotti/Projects/personal/electron-json-storage/node_modules/async/dist/async.js:969:16
      at /Users/jviotti/Projects/personal/electron-json-storage/lib/storage.js:150:16
      at nextTask (node_modules/async/dist/async.js:5324:14)
      at next (node_modules/async/dist/async.js:5331:9)
      at /Users/jviotti/Projects/personal/electron-json-storage/node_modules/async/dist/async.js:969:16
      at /Users/jviotti/Projects/personal/electron-json-storage/lib/storage.js:135:18
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

  3) Electron JSON Storage
       .getDefaultDataPath()
         should be a string:
     Uncaught AssertionError: expected undefined to equal 32866
      at /Users/jviotti/Projects/personal/electron-json-storage/tests/storage.spec.js:63:42
      at nextTask (node_modules/async/dist/async.js:5324:14)
      at next (node_modules/async/dist/async.js:5331:9)
      at /Users/jviotti/Projects/personal/electron-json-storage/node_modules/async/dist/async.js:969:16
      at /Users/jviotti/Projects/personal/electron-json-storage/node_modules/async/dist/async.js:473:16
      at next (node_modules/async/dist/async.js:5329:29)
      at /Users/jviotti/Projects/personal/electron-json-storage/node_modules/async/dist/async.js:969:16
      at /Users/jviotti/Projects/personal/electron-json-storage/lib/storage.js:152:14
      at nextTask (node_modules/async/dist/async.js:5324:14)
      at next (node_modules/async/dist/async.js:5331:9)
      at /Users/jviotti/Projects/personal/electron-json-storage/node_modules/async/dist/async.js:969:16
      at ReadFileContext.callback (lib/storage.js:139:18)
      at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

I'll hopefully work on this tonight, but feel free to attempt a fix until then!

**Comment by oscar-renteria** [comment]
Hi @jviotti, unfortunately, I cannot share the application but I can describe what it does.

> The locking we implemented only works if you're using electron-json-storage on one process, and doesn't protect you if you are writing to the same file from different processes.

That gave me a hint to probably solve my problem.

The application access the configuration file from the main process and one render process.
Usually, the main process only reads the config file when the application starts. BUT if the config file structure has changed (for example, a new property was added),  the config file will be updated on the main process. While this is happening, the render process starts and tries as well to perform read and write operations. Maybe the problem lies there.

I will refactor the code to avoid conflicts between main and render processes and report back! It could take some time to know if that worked or not.

Gracias!

**Comment by bithavoc** [comment]
nice, we use https://github.com/hardchor/electron-redux so we have an store in both processes. changes are we're also saving from both processes. Again, I'm gonna double check and report back.

**Comment by bithavoc** [comment]
@oscar-renteria @jviotti I'm only initializing the module from the main process, it's the safest way so there is no chance two processes are writing the same state.

**Comment by jviotti** [comment]
Hi guys. Good news! I believe I fixed this issue on this PR: https://github.com/electron-userland/electron-json-storage/pull/109. Would you mind giving a shot to confirm the issue is ruled out before merging and publishing? 

Basically the problem was that the locking module I was using was not doing real locking, but just some checks in-memory within the same process, so writing the file from more than one process would trigger the issue.

Let me know!

**Comment by jviotti** [comment]
Oops! I got the PR link wrong. I edited the original message, but just in case, here is the right one: https://github.com/electron-userland/electron-json-storage/pull/110

**Comment by bithavoc** [comment]
@jviotti I'll give it a try, although we double-checked and we're definitely not using the module from two process at the same time.

Should we start using the `proper-locking` branch from package.json?

**Comment by oscar-renteria** [comment]
Hi @jviotti, thank you for the update. I will try it and report back.

Maybe it is worth to mention that I have re-factorized my code and now the application only writes the config from one process. I have installed the new version on some machines where this issue was present. Until now everything has been running well.

And @bithavoc , thank you for the electron-redux tip. I will give it a try!

**Comment by jviotti** [comment]
> Should we start using the proper-locking branch from package.json?

You can test it from there, but I'll merge the PR, close the branch, and publish a new version as soon as we can confirm things work.

**Comment by bithavoc** [comment]
@jkleinsc I tried the branch, my app works. Want to merge?

**Comment by bithavoc** [comment]
oops, I mean to mention @jviotti ☝️

**Comment by jviotti** [comment]
Done! Check v4.1.1

**Comment by bithavoc** [comment]
Awesome thanks @jviotti you 🎸 buddy
