### ISSUE TITLE
Write files atomically

### ISSUE THREAD

**Issue by janekolszak** [electron-userland/electron-json-storage#45]
Hi!
Is data written atomically to the disc?

I'm using electron-json-storage as a simple database and it's important that in case of some kind of crash data will be in one of the well known states.

Thanks!

**Comment by jviotti** [comment]
Hey there!

This module uses the NodeJS file-system module to write/read to/from
files (e.g: `fs.writeFile`, `fs.readFile`) which are atomic to the best
of my knowledge, however notice that given the async nature of NodeJS
you should assume anything was written until the callback is called.

**Comment by jviotti** [comment]
I'm closing this, but feel free to re-open if needed!

**Comment by jviotti** [comment]
Very interesting! We should move to https://github.com/npm/write-file-atomic then. Happy to take a PR :)

**Comment by jviotti** [comment]
I got some time to work on this today. Check v4.1.6!
