### ISSUE TITLE
Corrupt JSON after multiple quick writes

### ISSUE THREAD

**Issue by davishmcclurg** [electron-userland/electron-json-storage#70]
I'm running into a sporadic "[Invalid data](https://github.com/electron-userland/electron-json-storage/blob/e33dd38705dbf569d931ea2806dfe48476559655/lib/storage.js#L88)" error that I think is caused by multiple writes happening in quick succession. The stored json is invalid, with an extra object at the end of the file (after the end of an array).

My guess is that it's caused by [`fs.writeFile`](https://github.com/electron-userland/electron-json-storage/blob/e33dd38705dbf569d931ea2806dfe48476559655/lib/storage.js#L196), because it's asynchronous and can cause issues like these: https://github.com/nodejs/node-v0.x-archive/issues/4965

I don't have a good test case at the moment, but I'll try to put something together if I get some time later.

**Comment by jviotti** [comment]
Hey there! 

That's a very interesting issue. I'm sending a PR which stress tests the module by writing and reading a lot of random numbers very quickly in a serial fashion, to see if that reveals anything, even though it always passes without issues on macOS (let's see what Linux and Windows say in the CI tests).

What OS are you running? Could it be that multiple parts of the code are trying to write to the same file at the same time, causing corruption?

If my serial stress testing cases pass, I'll investigate parallel ones.

**Comment by jviotti** [comment]
See https://github.com/electron-userland/electron-json-storage/pull/71

**Comment by jviotti** [comment]
BTW, are you running this module on the main or in a renderer process? Does it make any difference?

**Comment by jviotti** [comment]
I also just wrote and read 100k random items, for the sake of science, and it passes just fine.

**Comment by davishmcclurg** [comment]
Thanks for the quick response @jviotti. I'm running macOS as well and using the module in the main process. I haven't tested in a renderer, but I doubt it would make a difference.

I added a failing spec to my fork that should clear things up: https://github.com/davishmcclurg/electron-json-storage/commit/5a136d28f87aa5a642eabeb22cb01c5164035e4b

**Comment by jviotti** [comment]
Thanks a lot for the test case. I'll be working on it and see if I can devise a fix.

**Comment by jviotti** [comment]
I just sent a PR with a fix!

**Comment by jviotti** [comment]
Check v3.0.6 on npm!

**Comment by davishmcclurg** [comment]
Nice, thanks @jviotti. I'll try out the new version shortly. If you want to remove the `rwlock` dependency, I used `async/queue` to get around this in our app.

**Comment by jviotti** [comment]
Ah, cool, feel free to send a PR :)

**Comment by vietquocnguyen** [comment]
> Nice, thanks @jviotti. I'll try out the new version shortly. If you want to remove the `rwlock` dependency, I used `async/queue` to get around this in our app.

What do you mean by `rwlock` dependency? and using `async/queue`? Thanks
