### ISSUE TITLE
Cannot use get/setDataPath functions

### ISSUE THREAD

**Issue by seanmcclure22** [electron-userland/electron-json-storage#82]
Hi!

Whenever I attempt to use the storage.getDataPath/storage.setDataPath functions, I get a "TypeError: storage.setDataPath is not a function" error message.

I have the latest version of electron-json-storage and I can see the functions in my node_modules/electron-json-storage/storage.js file. Even when I copy the function out of the utils.js file and put it directly in storage.js I receive the same error.

I also tried installing the types/electron-json-storage, which seems to be out of date, and doesn't include these new functions.

Any advice?

Thanks!

**Comment by jviotti** [comment]
That's very weird. We even have tests that cover those functions (https://github.com/electron-userland/electron-json-storage/blob/master/tests/storage.spec.js#L98, https://github.com/electron-userland/electron-json-storage/blob/master/tests/storage.spec.js#L121). Are you absolutely sure you pulled the latest version from npm?

**Comment by seanmcclure22** [comment]
Yeah I am absolutely positive. I have version 3.1.0 which VSCode as well as the Github page suggest as the latest. 

I can see the methods in my node_modules/electron-json-storage folder so I think that is a good indication of having the latest version. 

I attached some images of the error, my version of electron-json-storage, and a code snippet of me attempting to call the setDataPath method.
![image](https://user-images.githubusercontent.com/11984816/30123846-8771aca2-92f0-11e7-950c-e3c1a720bf02.png)

![image](https://user-images.githubusercontent.com/11984816/30123906-b8b1da62-92f0-11e7-954d-77e47f89c841.png)

![image](https://user-images.githubusercontent.com/11984816/30123920-cbf08cea-92f0-11e7-9a00-fd766f772a4c.png)

**Comment by jviotti** [comment]
Strange... I tried again but I'm still not able to reproduce. Do you think you can build a small gist or something I can test over here? I'm happy to help you get to the bottom of it.

**Comment by seanmcclure22** [comment]
So it turns out my node_modules folder in my dist folder was not updating with the latest version of electron-json-storage, so I was seeing the updated version in my node_modules folder, but the application was pulling from the dist folder, which is why it was throwing this error.

Thanks for your responses.
