### ISSUE TITLE
Not storing values in windows platform

### ISSUE THREAD

**Issue by arkakkar** [electron-userland/electron-json-storage#83]
Hi,
electron-json-storage seems to work fine while working on a mac app, though on windows it does not create a particular storage json file under app.getPath('userData') directory. Could you help ? What am I doing wrong ?
Sometimes also creating an empty json file.
Have checked with the object I am setting to the key

**Comment by jviotti** [comment]
Hey there,

Do you have an actual error message? We test this module on Windows (using Appveyor CI), so I'm surprised it fails for you. Can you push the code somewhere I can take a look myself?

**Comment by arkakkar** [comment]
No I don't have an error message. It just empties the json file. I was trying to save to settings in the before-quit event. It seems to work fine on the mac platform. I have moved my code form before-quit handler to somewhere else and seems to be working fine now

**Comment by jviotti** [comment]
Weird. Let me know if it happens again, and try to build a small reproducible example that I can play around with.

**Comment by bachdinhnhan** [comment]
I have same problem with @arkakkar . 
Work fine on Mac platform but Window.
No crash, just silence on Window. I try to debug to see what's wrong

**Comment by bachdinhnhan** [comment]
Test input:
key: john6638@gmail*__dot__*com
value: an object

Result:
Error: ENOENT: no such file or directory, open 'C:\Path
To\storage\john6638%40gmail*__dot__*com.json'

**Comment by jviotti** [comment]
I see. The issue is that an asterisk is not a valid character for paths on Windows (not the case on other UNIX operating systems). Let me see what I can do

**Comment by bachdinhnhan** [comment]
Thanks for your reply.
I think that It will be fine to put a note on Readme

**Comment by jviotti** [comment]
@bachdinhnhan You're welcome! Check v3.1.1. It should work there!
