### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by jbw91** [electron-userland/electron-json-storage#85]
I have a use case where I want to have essentially multiple instances of this library, because I want to store various json files in various locations. With the single instance I have to always set the data path immediately before running the command, but that's not perfect in case I have two async tasks running and I end up with a race condition error. I couldn't find anything in the documentation about creating new instances of this library, with each instance having its own data path.

**Comment by jviotti** [comment]
Hi @jbw91 ,

Check https://github.com/electron-userland/electron-json-storage/pull/87. I added a way to pass a custom data path in all functions, which should do the trick!

**Comment by jviotti** [comment]
Check v3.2.0 on npm!

**Comment by jbw91** [comment]
> Check v3.2.0 on npm!

Looks like 3.2.0 isn't published to npm yet. Got an ETA on that?

**Comment by jviotti** [comment]
Oops, looks like I forgot about it. I should be good now!
