### ISSUE TITLE
'userData' bug reintroduced after 3.1.0

### ISSUE THREAD

**Issue by bingqiao** [electron-userland/electron-json-storage#86]
Electron allows the change of 'userData'. I remember there used to be a bug in electron-json-storage where the 'userData' is read upon loading electron-json-storage lib which means any change to it made in the electron app will just get ignored. This bug was fixed then reappeared in 3.1.0. There might be ways to change 'userData' before electron-json-storage gets loaded but this change of behaviour could break existing code.

**Comment by jviotti** [comment]
Hey there! Can you provide an example that reproduces the problem? I double checked and the user data path is indeed being dynamically queried on every call.

**Comment by bingqiao** [comment]
Before 3.1.0 the getUserDataPath is as follows:
```
 exports.getUserDataPath = function() {
   const app = electron.app || (electron.remote && electron.remote.app);

   if (app) {
     return path.join(app.getPath('userData'), 'storage');
   } else {
     return '/tmp/storage';
   }
 };
```
This is now changed to:
```
exports.getUserDataPath = function() {
  return currentDirectory;
};
```
Now a call to getUserDataPath just returns the value of currentDirectory. This is a change of behaviour.

This basically changes back to how it used to work prior to the change on 08/Jan/2017 when this bug was fixed.
The change on 08/Jan/2017 changed the following:
```
exports.getUserDataPath = function() {
  return userData;
};
```
to:
```
exports.getUserDataPath = function() {
  return app.getPath('userData');
};
```

What happens now is once this script is loaded, and if the user data path is changed by the electron app which happens after currentDirectory is assigned, then a call to getUserDatapath just gets the old value, the value assigned upon loading.

Thanks

**Comment by bingqiao** [comment]
The use case here is that I'm changing the userdata folder to a subfolder inside the default userdata. This stopped working after 3.1.0 where the json storage files start getting created inside the default userdata folder.

**Comment by jviotti** [comment]
Ahhh, I see what you mean now. I'll send a PR in a bit :)

**Comment by jviotti** [comment]
Check v4.0.0!
