### ISSUE TITLE
Option to store real json

### ISSUE THREAD

**Issue by achtan** [electron-userland/electron-json-storage#90]
is there a way to store real JSON format? 

why are you using `JSON.stringify` anyway? I assumed when the package name is `electron-json-storage` that it will store real json files... even the file extension name is '.json' but the content is in string :/

**Comment by jviotti** [comment]
JSON **is** a text-based format. Real JSON is the output of `JSON.stringify`. I think you're getting confused with JavaScript Objects, from where JSON originated. Every JSON string can be parsed as a JavaScript Object, but not every JavaScript Object can be stringified into JSON.
