### ISSUE TITLE
Does store.set() update or overwrite?

### ISSUE THREAD

**Issue by jsrbn** [electron-userland/electron-json-storage#99]
Hey, 
my question is whether the `store.set()` function overwrites **all** data inside the JSON path so e.g. when you got a path like `'foobar': {'foo': 'bar', 'bar': 'foo'}` and call `store.set('foobar', {'bar': 'bar'})`, does it remove the `'foo'` entry or does it just overwrite the `'bar'` entry and keeps `'foo'` alive?

**Comment by jviotti** [comment]
Hi @jsrbn ,

Your assumption is right; `.set()` will override the data at the selected key. You can implement a "merge" behaviour using a combination of `.get()` and `.set()`.

Hope that helps!
